# Generated by Django 3.1.7 on 2021-03-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='duration',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=20, null=True),
        ),
    ]
