# Generated by Django 3.1.7 on 2021-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0004_auto_20210323_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
