# Generated by Django 3.1.7 on 2021-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0005_auto_20210323_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image',
            field=models.ImageField(null=True, upload_to='frame_images'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
