# Generated by Django 3.1.7 on 2021-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0006_auto_20210327_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'verbose_name_plural': 'Frames'},
        ),
        migrations.AddField(
            model_name='frame',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
