# Generated by Django 3.1.7 on 2021-03-27 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0007_auto_20210327_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Frames',
            },
        ),
        migrations.AlterField(
            model_name='frame',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3-month', '3-Monthly'), ('6-month', '6-Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameCategories', to='frame.framecategories'),
        ),
    ]
