# Generated by Django 3.1.7 on 2021-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0008_auto_20210327_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framecategories',
            options={'verbose_name_plural': 'Frames categories'},
        ),
        migrations.AlterField(
            model_name='frame',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('3-month', '3-Month'), ('6-month', '6-Month'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
