# Generated by Django 3.1.7 on 2021-03-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
        ('products', '0002_auto_20210322_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products '},
        ),
        migrations.AlterField(
            model_name='categories',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frame.frame'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frame.frame'),
        ),
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
