# Generated by Django 3.1.7 on 2021-03-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0008_auto_20210327_1526'),
        ('products', '0003_auto_20210322_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='frame',
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame', to='frame.frame'),
        ),
    ]
