# Generated by Django 3.1.7 on 2021-03-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210327_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories'),
        ),
    ]
