# Generated by Django 3.1.7 on 2021-04-09 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0009_auto_20210330_0545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_belongs_to', to='frame.frame')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Products ',
            },
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Products ',
            },
        ),
    ]
