# Generated by Django 3.1.7 on 2021-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210413_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
