# Generated by Django 3.1.7 on 2021-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210413_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='frame',
        ),
    ]
