# Generated by Django 3.1.7 on 2021-04-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_orders_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
